image: ddev/ddev-gitpod-base:20240207

tasks:
  - name: ddev-gitpod-launcher
    init: |
      ddev debug download-images
    command: |
      export DDEV_NONINTERACTIVE=true
      cd ${GITPOD_REPO_ROOT}
      .gitpod/start_repo.sh

vscode:
  extensions:
    # PHP extension
    - felixfbecker.php-debug

    # Bash extensions
    - timonwong.shellcheck
    - rogalmic.bash-debug

ports:
  # Ignore direct-build https port
  - port: 2222
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  # Used by projector
  - port: 6942
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # Currently un-notified and unsupported mailhog http port
  - port: 8025
    onOpen: ignore
  # Currently un-notified and unsupported mailhog https port
  - port: 8026
    onOpen: ignore
  # Currently un-notified and unsupported phpmyadmin http port
  - port: 8036
    onOpen: ignore
  # Currently un-notified and unsupported phpmyadmin https port
  - port: 8037
    onOpen: ignore
  # router http port that we're ignoring.
  - port: 8888
    onOpen: ignore
  # router https port that we're ignoring.
  - port: 8889
    onOpen: ignore
  # xdebug port
  - port: 9000
    onOpen: ignore
  # projector port
  - port: 9999
