#!/usr/bin/env bash

PROJECT_NAME="$(basename "$DDEV_REPO")"

# Dynamically generate .gitmodules file
cat <<GITMODULESEND > "${GITPOD_REPO_ROOT}"/.gitmodules
# This file was dynamically generated by a script
[submodule "$PROJECT_NAME"]
    path = $PROJECT_NAME
    url = $DDEV_REPO
    ignore = dirty
GITMODULESEND
